ff-notes/ff

exe/Main.hs
exe/Options.hs
lib/FF.hs
package.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cblp/ff/4)

dates for notes

---

ff-core/lib/FF/Options.hs
ff/Main.hs
ff/package.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/46)

Version command

---

CHANGELOG.md

-V,--version 
from [Issue 24](https://github.com/ff-notes/ff/issues/24)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/48)

Version Upgrade

---

CHANGELOG.md
ff-core/lib/FF/Options.hs
ff/Main.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/49)

Fix version to --version, -v

---

CHANGELOG.md
ff/Main.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/52)

git dirtiness

---

ff-core/lib/FF/Github.hs
ff-core/lib/FF/Options.hs
ff-core/package.yaml
ff/Main.hs
ff/package.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/53)

Github list issues

---

ff-core/lib/FF/Github.hs
ff-core/lib/FF/Options.hs
ff/Main.hs

Пока не работает. Загвоздка в файле `Main.hs`  в строке 116:
`CmdGithub list -> liftIO $ runCmdGithub list`
где
`CmdGithub` принимает один аргумент, а `runCmdGithub` два. И не ясно, нужно дополнительную функцию писать или как-то здесь же можно реализовать.
Update: 
Нашел как сделать. Вопрос снят.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/54)

Choose repo by user and list as command

---

ff-core/lib/FF/Github.hs
ff-core/package.yaml
ff/Main.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/56)

taskMode to get proper state in ff github llist

---

ff-core/lib/FF/Github.hs
ff-core/lib/FF/Options.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/61)

limit via pagination

---

ff-core/lib/FF/Github.hs

no divide by 30 needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/62)

Fix fetch counting 

---

ff-core/lib/FF/Github.hs
ff-core/package.yaml
ff-core/test/Main.hs

Тест не проходит:
```haskell
> case_repo
*** Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "main", srcLocModule = "Main", srcLocFile = "/media/metaxis/stock/Coding/Haskell/ff/ff-core/test/Main.hs", srcLocStartLine = 262, srcLocStartCol = 5, srcLocEndLine = 262, srcLocEndCol = 21})) 
"expected: 
fromList [(Starting 365374,Sample {notes = [NoteView {nid = 334520780, status = Active, text = \"import issues (GitHub -> ff)\\nurl https://github.com/ff-notes/ff/issues/60\", start = 2018-06-21, end = Just 2018-06-15}], total = 1})]\n 
but got: 
fromList [(Overdue 10,Sample {notes = [NoteView {nid = 334520780, status = Active, text = \"import issues (GitHub -> ff)\\nurl            https://github.com/ff-notes/ff/issues/60\", start = 2018-06-21, end = Just 2018-06-15}], total = 1})]"
``` …

Add test for github list

---

ff-core/lib/FF/Github.hs
ff/Main.hs
ff/package.yaml

Не сильно код поменялся. Один _case_ сократился.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/65)

Add ExceptT

---

ff/Main.hs
ff/package.yaml

Такая конструкция отдельно делает все как надо, но в проекте во время загрузки данных с гитхаба, ничего не отображается, только потом после вывода виден _fetching..._.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/66)

Add dotting while fetching 

---

ff-core/lib/FF.hs
ff-core/lib/FF/Options.hs
ff/Main.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/68)

Added empty ff serve command

---

CHANGELOG.md
ff-core/lib/FF.hs
ff/Main.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/74)

Add blocking to edit tracked notes

---

ff-core/lib/FF/Serve.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/81)

ff serve command: some styling for better appearance

---

CHANGELOG.md
ff-core/lib/FF/Github.hs

Resolves [#78](https://github.com/ff-notes/ff/issues/78)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/87)

[#78] Track issue body

---

CHANGELOG.md
ff-core/lib/FF.hs
ff-core/lib/FF/Options.hs
ff-core/lib/FF/Types.hs
ff-test/test/Main.hs
ff/Main.hs

Resolves [#88](https://github.com/ff-notes/ff/issues/88)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/90)

[#88] Add wiki notes

---

.gitignore
CHANGELOG.md
ff-core/lib/FF.hs
ff-core/lib/FF/Options.hs
ff/Main.hs

Resolves [#97](https://github.com/ff-notes/ff/issues/97)
Resolves [#91](https://github.com/ff-notes/ff/issues/91)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/98)

[#91] Add wiki show

---

CHANGELOG.md
ff-core/lib/FF.hs
ff-core/lib/FF/Options.hs
ff-core/lib/FF/Serve.hs
ff-core/lib/FF/UI.hs
ff-test/test/Main.hs
ff/Main.hs

Переделал немного wiki вывод, чтобы он не захватывал `mode`, который для него не актуален.
В связи с этим ряд других функций оптимизировал. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/99)

Search in all docs

---

README.md

Information about developers chat has been added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/103)

[README] Update contact info

---

CHANGELOG.md
ff-core/lib/FF/Options.hs
ff/Main.hs

Resolves #109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/110)

Option to specify work directory

---

CHANGELOG.md
ff-core/lib/FF/UI.hs
ff-core/package.yaml
ff/Main.hs
ff/package.yaml
stack.yaml

Resolve #95 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/113)

Add colors

---

ff-qt/ff-qt.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/134)

Add Qt paths for Arch Linux

---

.vscode/tasks.json

Resolve #149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/150)

Add vscode tasks

---

CHANGELOG.md
README.md
ff-core/lib/FF/Options.hs
ff-test/ff-test.cabal
ff-test/test/Main.hs
ff-test/test/Readme.hs
stack.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/155)

Add readme test

---

ff-core/lib/FF.hs

Resolves #139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/156)

Make error comprehensible

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/160)

Fix Travis config for GTK

---

ff-core/lib/FF.hs
ff-core/lib/FF/Github.hs
ff-core/lib/FF/Types.hs
ff-core/lib/FF/UI.hs
ff-gtk/Main.hs
ff-qt/Main.hs
ff-test/test/Database.hs
ff-test/test/Gen.hs
ff-test/test/Regression.hs
stack.yaml
stack.yaml.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/165)

Update ron to 0.8

---

ff-core/lib/FF.hs
ff-core/lib/FF/CLI.hs
ff-core/lib/FF/Types.hs
ff-core/lib/FF/Upgrade.hs
ff-qt/Main.hs
ff-test/test/Database.hs
ff-test/test/Main.hs
ff-test/test/Regression.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/164)

Upgrade Note to ORSet rep

---

stack.yaml
stack.yaml.lock

to fix https://github.com/haskell-gi/haskell-gi/issues/230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/167)

Update haskell-gi to 0.22.4

---

shell.nix
stack.yaml

Add needed packages to stack.yaml and shell.nix file for development environment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/166)

Add build files for nix

---

README.md
ff-core/lib/FF.hs
ff-core/lib/FF/CLI.hs
ff-core/lib/FF/Github.hs
ff-core/lib/FF/Options.hs
ff-core/lib/FF/Types.hs
ff-core/lib/FF/UI.hs
ff-gtk/Main.hs
ff-qt/Main.hs
ff-test/test/Database.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/173)

Filter notes by tags

---

ff-core/lib/FF.hs
ff-core/lib/FF/Options.hs
ff-core/lib/FF/UI.hs
ff-test/test/Database.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/174)

Add ability to create note with tags

---

ff-core/lib/FF.hs
ff-core/lib/FF/Options.hs
ff-qt/FFI/Haskell.hs
ff-qt/ff-qt.cabal
stack.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/175)

Add option to add tags to existing note

---

ff-core/lib/FF.hs
ff-core/lib/FF/Options.hs
ff-qt/FFI/Haskell.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/176)

Add option to remove tag from note

---

ff-core/lib/FF.hs
ff-core/lib/FF/Github.hs
ff-core/lib/FF/Types.hs
ff-core/lib/FF/UI.hs
ff-gtk/Main.hs
ff-qt/Main.hs
ff-test/test/Database.hs
ff-test/test/Regression.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/184)

Add extended Entity' and EntityView

---

stack.yaml
stack.yaml.lock

Resolves #182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/185)

Bump up githab dependency to 0.23

---

README.md
ff-core/lib/FF.hs
ff-core/lib/FF/CLI.hs
ff-core/lib/FF/Options.hs
ff-core/lib/FF/UI.hs
ff-test/test/Database.hs

Resolves #178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/186)

Filter untagged note

---

ff-qt/Main.hs
ff-qt/ff-qt.cabal
stack.yaml
stack.yaml.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/187)

Small update of ron-storage dep

---

CHANGELOG.md
README.md
ff-core/lib/FF.hs
ff-core/lib/FF/CLI.hs
ff-core/lib/FF/Options.hs
ff-test/test/Database.hs

Resolves #179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/193)

Without specific tags option (#179)

---

ff-qt/Main.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/194)

Fix memory use after free

---

ff-core/lib/FF.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/196)

Refactor viewTaskSamplesWith

---

ff-core/lib/FF.hs
ff-core/lib/FF/CLI.hs
ff-gtk/Main.hs
ff-qt/Main.hs
ff-test/test/Regression.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/195)

Rename toNoteView -> viewNote

---

ff-qt/Main.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/198)

ff-qt: Fix GHC RTS stuck on tryReadTChan

---

CHANGELOG.md
ff-core/lib/FF/CLI.hs
ff-core/lib/FF/UI.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/200)

Show path everywhere (#105)

---

ff-core/lib/FF.hs

To improve UX of VS Code usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/209)

Use `txt` extension for temporary externally edited files

---

ff-core/lib/FF.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/207)

Add error message when EDITOR is bad

---

ff-core/lib/FF.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/208)

Add message about waiting for editor

---

README.md
ff-core/ff-core.cabal
ff-core/lib/FF.hs
ff-core/lib/FF/Options.hs
stack.yaml
stack.yaml.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/210)

Add ability to use shell command as editor

---

.travis.yml
ff-qtah/FF/Qt.hs
ff-qtah/FF/Qt/DateComponent.hs
ff-qtah/FF/Qt/MainWindow.hs
ff-qtah/FF/Qt/TaskListWidget.hs
ff-qtah/FF/Qt/TaskWidget.hs
ff-qtah/Main.hs
ff-qtah/ff-qtah.cabal
stack.yaml
stack.yaml.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/218)

Add ff-qtah

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/222)

Travis: Use apt declaratively

---

.travis.yml
stack.yaml
stack.yaml.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/221)

Update Travis config to use Ubuntu 18

---

ff-qtah/FF/Qt/MainWindow.hs
ff-qtah/FF/Qt/TaskWidget.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/224)

ff-qtah: Make task widget scrollable

---

ff-core/lib/FF.hs
ff-core/lib/FF/CLI.hs
ff-core/lib/FF/Config.hs
ff-core/lib/FF/Options.hs
ff-test/test/Config.hs
ff-test/test/Gen.hs

This is my first Haskell contribution, so please be kind ;-) Please let me know if there is a better way 
Fixes #213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ff-notes/ff/227)

Add config parameter for external editor
